### ISSUE TITLE
Fresh 64bit install .. "Configure presets..." is all I can see.

### ISSUE THREAD

**Issue by Admin225580** [Tichau/FileConverter#103]
Hello. Just found and installed FileConverter, and verified my systems meets the .net requirement. From the very first time I right clicked a video and chose File Converter, the only option I see is "Configure presets..." so I clicked that and modified one entry (mp3) and clicked Save.   Repeated the process and get the same result, only "Configure presets..." 

![sample snip](https://user-images.githubusercontent.com/47673299/76524875-33077500-6441-11ea-8aaf-51c0b97f8ae4.JPG)

 What am I doing wrong?  OS: Win10 1809 Build 17763.1039 ... 64 bit installer used.. also here's what I see under Configure presets... and I exit with the Save button.  Also tried uninstalling and reinstalling the application, with no difference.

![FC settings](https://user-images.githubusercontent.com/47673299/76524930-503c4380-6441-11ea-86ad-86dfbae7baeb.JPG)

Thanks for any assistance, I look forward to using this converter.

**Comment by Admin225580** [comment]
Bueller?

**Comment by Ham6YC** [comment]
I had the same problem. I found that I can use file converter from the context menu when I installed it from an admin account and was logged in as admin. When I didn't install fc as admin and/or wasn't logged in as admin, I experienced the same isue as described above. (as in screenshot: only option was 'configure presets' - I chose 'save' - there was no change in behaviour of the context menu afterwards)
Even worse. The registration of jpg-files was gone and a weird error occurred when I double-clicked on jpg-files. Sorry for not having screenshot the error-messages after double-clicking on jpgs... I panicked into deinstalling 'file-converter' and after that only by installing irfanview (I think any other viewer would have done the same job...) and registering 'jpg' to it, I regained access to jpg-files.
My installation file was FileConverter-1.2.3-x64-setup.msi
My Windows Version is: Microsoft Windows [Version 10.0.18363.720]
![FileConverterScreeshot_notAdmin](https://user-images.githubusercontent.com/62912449/77968485-be10b800-72e7-11ea-98e6-8fab6bd4d2f0.jpg)

**Comment by Admin225580** [comment]
> I had the same problem. I found that I can use file converter from the context menu when I installed it from an admin account and was logged in as admin.

No worries about screenshots, I thank you for your reply. I will try admin login / install !

**Comment by sphatrick** [comment]
I've got the same issue.  I installed on my home computer, where I am an admin, and it works great.  I then had one of the IT Admins at work install it on my work machine (where I'm not an admin) and the only option I get is Configure Presets.

**Comment by trishf42** [comment]
Can confirm. If file converter is installed by admin, only admin can use it; even if the user is escalated to a local admin, only Configure Presets is available.

**Comment by Tichau** [comment]
Hello, thanks for the feedback. For now File Converter is not working on Non-admin users. I need to work on this as soon as I can.

Duplicates #4
