### ISSUE TITLE
Cannot make donation

### ISSUE THREAD

**Issue by WhitePhoenixUS** [Tichau/FileConverter#104]
Cannot access Pledgie: The connection has timed out

The server at pledgie.com is taking too long to respond.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that IceDragon/Firefox* is permitted to access the Web. *I used them both.

**Comment by lucasbfr** [comment]
The good news is that it seems to be working again :)

**Comment by Tichau** [comment]
Hi!
Thanks for trying to send a donation :). I've started to move the donation site on another platform but forgot some links ^^
Here is the new link on [Paypal](https://www.paypal.com/donate/?cmd=_donations&business=3BDWQTYTTA3D8&item_name=File+Converter+Donations&currency_code=EUR&Z3JncnB0=)

The link on FileConverter website has already been changed, the link in the application will be changed on the next release.
