### ISSUE TITLE
Unable to convert .ogg to .mp3

### ISSUE THREAD

**Issue by CT-8551** [Tichau/FileConverter#107]
trying to convert an ogg audio file to an mp3, i get the error : 
error while decoding stream #0:0: invalid argument.
here are some images.
https://imgur.com/bxGxBJk
https://imgur.com/2PU9aL3
https://imgur.com/DD6nZXY
https://imgur.com/PjuUiTl

**Comment by Tichau** [comment]
The error come from FFMPEG (the software that is doing the conversion). Your file seems to be corrupted, if not, you can open an issue on the FFMPEG project.
