### ISSUE TITLE
PDF files wrong interpretation (background is not correct)

### ISSUE THREAD

**Issue by krasi533513** [Tichau/FileConverter#108]
**Hi!
First I want to say - thanks for that very useful project!**

I have noticed that some PDF input is not correctly interpreted - I can send you a simple PDF, 2 pages document to show that issue.

The first page comes out wrong with black background, but the second one is correct - with white background...

Almost the same is result with that PDF converted to Paged PNG....

[408593405.pdf](https://github.com/Tichau/FileConverter/files/4482760/408593405.pdf)
![408593405](https://user-images.githubusercontent.com/11940008/79368130-95c7c100-7f57-11ea-95c2-ee3cb40fc374.jpg)
![408593405 (2)](https://user-images.githubusercontent.com/11940008/79368139-98c2b180-7f57-11ea-92e9-8c7dbb6db545.jpg)

**Comment by Tichau** [comment]
Duplicates #66

**Comment by getopian** [comment]
Anyone will fix it bros?

**Comment by djcurley89** [comment]
> Anyone will fix it bros?

Dude shut up
