### ISSUE TITLE
No presets showing when right-clicking, after install

### ISSUE THREAD

**Issue by fongaboo** [Tichau/FileConverter#123]
When I right-click any supported file and hover over the File Converter option, it only shows 'Configure Presets'. When selecting that, it opens up Settings, where I can see many presets already created. But there is no obvious way to activate them so they appear in the right-click menu.

**Comment by Redtwist27** [comment]
Same issue here only ''configure presets' does appear.

**Comment by Manni79** [comment]
whats the state on this?

**Comment by alcadel** [comment]
Same here !
@Tichau is there any chance to see this issue fixed ? (BTW, looking forward to Humankind :))

**Comment by lakruad** [comment]
Same issue if an account with no administrator privileges. Make a user an admin and you fix it. In my case.

**Comment by Maschinist242** [comment]
That's exactly the tool I search for so long ... but same issue here. 
@lakruad: It also doesn't seem to work with an admin account.

**Comment by TheChilliPL** [comment]
Same here

**Comment by Manni79** [comment]
Seems to be a dead github project for me. This and also all the other github threads do not get answers.

**Comment by djcurley89** [comment]
Not sure why you guys are having this issue but I'm on the latest windows update and it still works fine. Something else may be going on with your setup.

**Comment by Maschinist242** [comment]
@djcurley89: Seems you're working with local admin permissions, didn't you? Please, can you confirm. I guess most of us with this issue doesn't.

**Comment by djcurley89** [comment]
> @djcurley89: Seems you're working with local admin permissions, didn't you? Please, can you confirm. I guess most of us with this issue doesn't.

I am the admin for my PC yes

**Comment by Tichau** [comment]
Hello, 
Thanks for reporting this issue. For now File Converter is not supported on User account. I close this issue and keep the initial issue reporting this problem to easily track the issue.

Duplicates #4
