### ISSUE TITLE
I can't convert to mp3 under 32k

### ISSUE THREAD

**Issue by Ricknds** [Tichau/FileConverter#124]
Hi!

Congratulations for the fantastic work done on this excellent and extremely useful application!

I would like to inform you that, despite creating a configuration for 24k and another for 16k, all the generated files are in 32k.

When using ffmpeg to achieve this setting, I always lower the sample rate to 22050-Hz. I didn't see how to change that in your program.

If you can help me, thank you very much !!

**Comment by Tichau** [comment]
You will be able to do it in the next version of File Converter by using custom advanced preset.
