### ISSUE TITLE
MP4 filters error

### ISSUE THREAD

**Issue by x10sys** [Tichau/FileConverter#125]
Great tool and thank you for it.
I have a problem with certain MP4 files - I get "Error opening filters!" error

[Video Information]
  Codec: AV01 - Built-in FFmpeg Decoder(libdav1d)
  Input type: AV01(24 bits)
  Input size: 400 × 224(1.79:1)
  Output type: NV12(12 bits)
  Output size: 400 × 224(1.79:1)
  Frame rate: 23.917
  BitRate: Unknown

I've managed solve my problem by updating ffmpeg with the latest build.

**Comment by Tichau** [comment]
Thank you for the feedback, I will update FFMPEG in the next release.
