### ISSUE TITLE
Video to H265 (HEVC) or between H265 quality

### ISSUE THREAD

**Issue by RFburn** [Tichau/FileConverter#128]
I have quite a few H265 videos and rely on the codec for smaller but higher quality videos vs. H264 that I see used currently h264 seems to be the only MPEG format supported for output, and unless I am blind I didn't see a way to add another option for MP4-HQ-Low/Med/High which I would like to have to reencode old H264 footage or make changes to existing H265 files. I just realized there has been no updates in 4 years so I may be talking to myself but this is an immensely useful tool for people who are lazy like me and don't want to open an app just to go through all the steps needed to queue each conversion so, while I may never see this change unless I do it myself (see the lazy comment) if anyone else has a solution with this ability, I will love you to the moon and back (and that is it) if you had any suggested alternatives. Ok, maybe I am not as lazy as I said and a conversion option with VIDEo (custom) might be nice too so if I select 10 files, I can set the preset values I want for those files, but not create an actual preset, just a one time use preset (that maybe also persists the next time you click custom in case you had another 5 files but maybe just wanted to tweak something about them a little bit.

Thanks, though I assume I'll never see a 1.2.4 because why would you want to progress pass an epic milestone such as 1.2.3?

**Comment by djcurley89** [comment]
Lol you're not talking to yourself, a lot of us would like to see some updates to this great app, but I don't see it happening unfortunately.

**Comment by Tichau** [comment]
Hello,
You will be able to create some custom preset in the next release (and so able to use h265). 
I'll keep this issue to open to think about changing the default codec to h265.
Thanks for reporting this issue.

**Comment by Tichau** [comment]
It is now possible to create a custom preset that uses H265 by using the advance mode.

I've opened this issue to talk about moving to H.265 as a default option : https://github.com/Tichau/FileConverter/issues/386
