### ISSUE TITLE
Webp to Gif

### ISSUE THREAD

**Issue by JrmyBm** [Tichau/FileConverter#134]
Im loving that contextual tool yu are offering. I'm looking to convert mostly webp animated pictures back into gif. Unfortunately FileConverter doesn't work for me in that matter. Most of the gif i download on the web are automatically convert into webp right now on most of the explorers such as firefox, chrome etc... I use discord a lot and discord does not support webp. Im using Windows7, maybe is that part of the issue here? I found another post from 2018 with the exact same issue. Any clue on what we are doing wrong? Thx a lot for the tool and hope to get an answer around here, Hugs

**Comment by Tichau** [comment]
Duplicates of #38 issue. 

This is a known bug, I've annotated the issue from 2018 with some details. For now, the wepb to gif conversion is not working. Sorry.
