### ISSUE TITLE
Converting videos to certain resolution

### ISSUE THREAD

**Issue by AlexFundorin** [Tichau/FileConverter#136]
Let's say I have a bunch of videos from my phone, both portrait and landscape, shot in 4k. 2160x3840 and 3840x2160. I also have some lower resolution videos in the same folder.
What I want is to have a preset to batch convert them, so that the largest dimension of the resulting videos is equal to 1920, but only if the original largest dimension was greater than 1920.
The end result would be 2160x3840 > 1080x1920, 3840x2160 > 1920x1080 and the low res vids ignored.
Is this scenario possible with File Converter?

**Comment by Tichau** [comment]
This will be possible in the next version of File Converter. There will be a new "Custom Preset" feature that will allow you to do that.
