### ISSUE TITLE
keep date

### ISSUE THREAD

**Issue by saladgoat** [Tichau/FileConverter#139]
If it's at all possible, I would love it if the program could retain the original file date for the converted output. At least to have the option to do so, for users to choose or not.
Thanks!

**Comment by thatscraigz** [comment]
Just was going to convert one of my archives and realized I was going to lose the date (not an issue for new things). But gosh such a gut check seeing decade old files and realizing "yeahhh I'd love to keep that if I could.." or at least put into the filename? 🤷‍♂️
