### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Khidreal** [Tichau/FileConverter#14]
Hi,
I would like to translate File Converter into my language, is it possible?

**Comment by Tichau** [comment]
Hi,

Yes ! this is very possible :) 
I made a tutorial here -> [Localization](https://github.com/Tichau/FileConverter/wiki/Localization)
If there are some parts that are not clear, don't hesitate to ask me some precisions, I'll be glad to help you and improve the tutorial.

Then, I'll integrate your translation in the next version of File Converter as soon as possible.

**Comment by Khidreal** [comment]
ok, most is done. can you tell me how to duplicate the file?
and how do I edit it, rigght on edit mode on github or should I just copy and paste it into a text editor like Atom and work there?
just to clarify (since I never used a resx file type before), I should translate what comes in front of the "=" right? like translate name=name into name=Nome? same as a xml file?
sorry to ask, I am an amateur, I love software and stuff related to computers and online services, but I can't help more the software I love than translating them... have not enough knowledge to contribute in other way...

**Comment by Tichau** [comment]
There is no problem to ask :) it is the best way to learn how to do stuff. Work on translation is a very important contribution! you allow a lot of new people to access to the software.

The resx file works like an xml file. And must not change what is in front of the =. the name part is the key I use in the software. You should edit what is inside the `<value></value>` tags. 

for example:
 ```
 <data name="AudioTitle" xml:space="preserve">
    <value>Audio translation</value>
  </data>
```

You can edit then direclty on github, but you should use a text editor, it will be easier for you.

**Comment by Tichau** [comment]
The cleaner way to propose changes on GitHub is to use the fork & pull request workflow. 
Basically you fork the repository you want to contribute to, then you make modifications on your fork of the repository. Finally you propose your modifications to the original repository by making a pull request.
Here is an explanation of this workflow and how to use it: [GitHub Standard Fork & Pull Request Workflow](https://gist.github.com/Chaser324/ce0505fbed06b947d962)

If you don't want to work that way you can also send me the file you created on this thread, since it is only one file I will be able to integrate it easily.

**Comment by Khidreal** [comment]
started today working on the translation. I'd like to test the translation before making the pull request to ensure everything is good, how can I do it, can you tell me?

**Comment by Khidreal** [comment]
also, may I have the liberty to trade stuff like
"this options allows you to change what happens with the input file, if the conversion is succesful"
into
"if the conversion is succesfully, what would you like to do with the input file?"
or do you want me just to keep the original format? I am asking because I think that puting a question makes it simpler and more user friendly (and also a smaller sentence).

**Comment by Khidreal** [comment]
translation complete. as I said, I would need to test it, rework it and send it to you again, I am pretty much sure there are things in there that don't really make sense, but I would need the translation available on File Converter in order to do things properly. it's here attached as resources.pt-PT.zip... wanted to make a pull request but I have no clue on how to do it :D
[Resources.pt-PT.zip](https://github.com/Tichau/FileConverter/files/705570/Resources.pt-PT.zip)

**Comment by Tichau** [comment]
Hi,

I agree for the change in the English loc, "if the conversion is succesfully, what would you like to do with the input file?" is better :)

To test your work, there is two solutions:
- fork the repository in your github, then clone it on your pc. Install [https://www.visualstudio.com/vs/community/](Visual Studio Community) then open FileConverter.sln to open the project. Then follow the instructions of my tutorial.
- Or I can make a test build for you (probably tomorrow)

**Comment by Tichau** [comment]
I compiled your localization file, it seems to works well.
Here is the file: [Languages.zip](https://github.com/Tichau/FileConverter/files/710270/Languages.zip)
You need to paste this archive in C:\Program Files\File Converter\Languages\ and uncompress it.
You should then be able to test your traduction.

**Comment by Khidreal** [comment]
sorry to inform you but your compiled file does not work. I can see the portuguese language available to choose on the drop down menu, but the text will just remain in english... I tested changing from eng into french and it works well, but not from EN to PT or FR to PT.
I pasted the file on the exact location you said and I also checked my translation and it's indeed translated.

**Comment by Tichau** [comment]
Ok, 
I created a test version of File Converter. You can download it here [FileConverter-1.2.1-x64-localization-test-setup.msi](https://expirebox.com/download/22645277864e9a29799a619486b91d71.html)
The link will be available for 48h.

Normally you should be able to have your translation available.

**Comment by Tichau** [comment]
Did you succeed to test the translation ?

**Comment by Khidreal** [comment]
actually no...
I've been really busy with work and only today came home (I am at the army)...
unfortunately, I installed that test version but my localization was not available, only french and english.
the best bet would be, in my opinion, for you to integrate the localization into File Converter, maybe someone else will pick it up and correct the problems, if there are any with the localization. this way the localization will not be lost, and if someone sees it already done maybe that person will correct it.
right now I can do nothing, tomorrow, sunday, I'll be on my way down to my military unit and I will, probably, not be comming home for at least another 20 days...

**Comment by Tichau** [comment]
Ok thanks again for your work!
I will publish your traduction soon and we will fix it later if there are some errors.

Take care.

**Comment by Tichau** [comment]
I've just publish the version 1.2.2 that contains your translation.

Thanks again for your work!
