### ISSUE TITLE
Keep two audio channels?

### ISSUE THREAD

**Issue by Wizek** [Tichau/FileConverter#140]
When I record a clip with nVidia ShadowPlay, it saves the video file with 2 audio channels, which is good. One for PC speaker output, one for microphone input. However, the resulting video file is huge and very poorly optimized, so I sometimes want to reduce this via FileConverter, especially when the file size is more important to be small than the video quality to be high. But I can't seem to get FileConverter to keep both audio channels in the resulting file; it seems to just pick one and discard the other. Can I somehow persuade FileConverter to keep both? Or could this be an option in settings, perhaps a tick box, whether to keep all audio channels or only one, because then I could tick that box at least there.

**Comment by Tichau** [comment]
It is now possible to create custom preset directly with ffmpeg arguments in the advance mode. You should be able to do this by looking at the ffmpeg documentation : https://ffmpeg.org/ffmpeg.html
