### ISSUE TITLE
Problems with Word files

### ISSUE THREAD

**Issue by lemonnuggets** [Tichau/FileConverter#143]
Whenever I try to convert a .doc or .docx document to .pdf it always fails and shows this error message

```The message filter indicated that the application is busy.  (Exception from HRESULT: 0x8001010A(RPC_E_SERVERCALL_RETRYLATER))```

And I then get a bunch of pop-ups asking if I want to make Word my default word processor.
Since I use LibreOffice, Microsoft Office isn't my default word processor.

**Is there any way to use FileConvert without changing my defaults?**

**Comment by Tichau** [comment]
File Converter only works with Microsoft Office. It is not possible to convert docx if you don't have it installed for now.

**Comment by Jack84Jack** [comment]
I have Microsoft Officce installed but it does not allow me to convert to pdf. a message appears saying "export failed. The feature is not installed".
Why does this happen?
