### ISSUE TITLE
Run utility in a batch file

### ISSUE THREAD

**Issue by TonyFrend** [Tichau/FileConverter#148]
I can run the utility using a command line in a normal Command Window ad the utility works as expected, popping up the usual 'progress' box counting down the 2 second delay.

Example command line:

"C:\Program Files\File Converter\FileConverter.exe" --conversion-preset "To Pdf" "C:\Test.doc"

However, if I run the same command via a batch file, the batch file hangs at the above command line.

I suspect that this is due to the fact that the 'progress' box tries to pop up and cannot.

**Comment by Tichau** [comment]
This feature is already referenced in issue #117
