### ISSUE TITLE
Only showing Configure Presets: Windows 10 Registry won‘t work again

### ISSUE THREAD

**Issue by OWL4C** [Tichau/FileConverter#149]
As in the Title, found a bug where the only option is to configure presets. Also the Options cant be saved, it seems that the program can‘t write to Registry. Found a workaround from a years old issue (#32) but this workaround is writing the config yourself in the registry. 
Is there any reason why you use the registry for user config? Wouldn‘t Appdata be easier to access and less error-prone?
Edit: I‘m guessing using a Admin-Account should enable Regediting by default, but since my account is not for security reasons, this becomes a real PIA, having to add presets manually.

**Comment by Tichau** [comment]
Hello, yes I planned to move settings stored in registry in another place in order to fix the issue #32. I just didn't had time to do it for now.

**Comment by OWL4C** [comment]
That sounds great! I just wanted to thank you, this is outstanding work anyhow! And not everyone even wants to dedicate his time for something like this.
