### ISSUE TITLE
Cannot convert .m4v to .mp4 video files

### ISSUE THREAD

**Issue by Diegovz01** [Tichau/FileConverter#151]
Every time I try to convert a .m4v video file into .mp4 it throws the following error message:

![image](https://user-images.githubusercontent.com/12522637/108149262-11bef800-7098-11eb-84e5-df000a4c26ff.png)

**Comment by Liverrrrr** [comment]
almost certainly because m4v file is drm protected. I will openin a new feature request for drm removal
