### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by tehUsual** [Tichau/FileConverter#16]
When I try to convert a .png to a 25% .png, it gets stuck on "in queue" before the system freezes and the memory usage climbs forever at a rate of 1GB 1-2 seconds.

Just got the program today, looks real promising!

**Comment by Tichau** [comment]
Hi!

Thanks for the report, I'm glad you find the soft cool :)

The bug you are describing is already known (https://github.com/Tichau/FileConverter/issues/5). 
I've succeeded to fix it and to finalizing a version that I should push probably this week.

Thanks again !

**Comment by Tichau** [comment]
The issue has been fixed in version 1.2.2
