### ISSUE TITLE
[Feature Request] TS convertion file support

### ISSUE THREAD

**Issue by rc-bandit4461** [Tichau/FileConverter#160]
You read it! add .ts input format to video conversion presets 👀

**Comment by nunoperalta** [comment]
Just came here to suggest the same! 👀

**Comment by nunoperalta** [comment]
To convert manually, we can use ffmpeg directly:

`ffmpeg.exe -i input.ts output.mp4`

**Comment by Tichau** [comment]
Duplicates of issue #23
