### ISSUE TITLE
Windows 10 standard (limited) user cannot add presets to context menu

### ISSUE THREAD

**Issue by funlul** [Tichau/FileConverter#176]
On the same computer, an administrator account can easily use presets through the context menu, but a standard user cannot. Every time it shows "configure presets" regardless how many times the user attempts to save by entering admin password. Problem resolved if the same user is elevated to local admin. 

Is there anyway to give FileConverter permission (registry?) so standard users can set it up by entering administrator password without actually being the administrator? Thank you very much!

**Comment by caedium** [comment]
+1
Same problem for me
