### ISSUE TITLE
USE H.265

### ISSUE THREAD

**Issue by Shituation** [Tichau/FileConverter#178]
Can we have H.265 using NVENC?

**Comment by dhry** [comment]
Does it even support x265/HEVC at all??

**Comment by elcosomalo1** [comment]
It uses FFMPEG. Actual versions do support it. I remember playing with the code a little and found a way to switch the command sent to ffmpeg to use H265. Then formatted the machine and lost it. Devs could do it really easily but this soft seems abandoned.

**Comment by Tichau** [comment]
duplicates of #128
