### ISSUE TITLE
Feature request: possibility to speed up or slow down video/audio file

### ISSUE THREAD

**Issue by nadege** [Tichau/FileConverter#18]

**Comment by Tichau** [comment]
Here is a preset folder that you can import with File Converter 2 to change speed of audio files : [Preset file](https://github.com/Tichau/FileConverter/blob/integration/PresetSamples/ChangeSpeedOfAudioFiles.xml)

You can dig here to make it works with video ([ffmpeg documentation](https://trac.ffmpeg.org/wiki/How%20to%20speed%20up%20/%20slow%20down%20a%20video#:~:text=You%20can%20speed%20up%20or%20slow%20down%20audio,up%20to%20no%20more%20than%20100x%20the%20input%29.)), I did not succeed to make it works easily.

:)

**Comment by Tichau** [comment]
This will be integrated in default preset in the next patch.
