### ISSUE TITLE
It does not work on users without administrator permissions ☹

### ISSUE THREAD

**Issue by DrakoAI** [Tichau/FileConverter#183]
I installed it on a PC with windows 8 and as administrator it works perfectly, but when changing to a user account without administrator permissions, it only shows the configuration option in the contextual menu.

![FileConverter](https://user-images.githubusercontent.com/44076746/127608035-b39d39f6-1009-4a95-af0f-0327e49d45f1.png)

**Comment by ValentinKhmer** [comment]
Can you send the `Settings.user.xml` file of the no-administrator account pls ?
_Notice: `⊞+R` and write `%localappdata%\FileConverter`_
