### ISSUE TITLE
Feature request: Copy Audio/Video stream (Remux), h.265, Change AspectR...

### ISSUE THREAD

**Issue by BooSN** [Tichau/FileConverter#19]
Useful feature would be:

Copy Audio and/or Video stream without encoding (Remuxing)
h.265 (x265 in ffmpeg) support 
Change Aspect Ratio in Container flags (w/o re-encoding)
Resizing by numbers (in addition to %)
Cropping 
Custom ffmpeg command line (to add special filters like deinterlace etc)

If you fear this will break "easy mode" maybe you can add an "Advanced" button/mode.

**Comment by Tichau** [comment]
Hi,

Indeed, I was afraid of making the interface to complex to add these features. But the ID of an advanced mode to enter a custom ffmpeg command is very good. I will think about that.

Thanks for the feedback
