### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by xaryangupta** [Tichau/FileConverter#190]
Can you pls update this thing. The last commit was 3 months ago, but the last build is 3 yrs old.

**Comment by K0media** [comment]
Wondering about the same thing... Is the project dead and deprecated? Or is the dev still working on it?

**Comment by Cwpute** [comment]
Wondering all the same.

**Comment by IntoTheVoid-900** [comment]
Even newer commits, but still no updates. I love this app, and there are no good FOSS alternatives. Please start developing this again! (PS I would love a workaround to convert PowerPoints to other formats without having PowerPoint installed for my FOSS app setup)

**Comment by Tichau** [comment]
I'm currently trying to clean up the issue board and will make a build with all the fixes and addition of the past years.

I'm working on that project on the side so I cannot put hours regularly in it (this is why the project feels abandonned).
