### ISSUE TITLE
Right click no options appear after install for tifs?

### ISSUE THREAD

**Issue by markm75** [Tichau/FileConverter#191]
Not sure if im just missing something simple but after install of 1.2.3 i dont see right click options (on tifs)?

EDIT: i see the issue, i have .tif files not .tiff, dont see a way to modify this.

**Comment by ForgedTurbo** [comment]
> It is normal because the software don't support this type of file. ![image](https://user-images.githubusercontent.com/72650892/136193756-f43fc886-dd0f-4f0f-934e-e2b95d9dbbc9.png)

But are they not the exact same file format? 
From Wikipedia: "Tag Image File Format, abbreviated TIFF or TIF..."



> Not sure if im just missing something simple but after install of 1.2.3 i dont see right click options (on tifs)?
> 
> EDIT: i see the issue, i have .tif files not .tiff, dont see a way to modify this.

If you just change the files extensions to .tiff, the converter will pick them up and it works just fine.

**Comment by Tichau** [comment]
duplicates of issue #29
