### ISSUE TITLE
CPU temp goes up to 90+ celsius

### ISSUE THREAD

**Issue by Veal-Uneasily4** [Tichau/FileConverter#195]
CPU: AMD 3600 (Stock fan cooler, it sucks I know)
I am scared to use the software. i dont want my pc to blow up.
Any solution?

**Comment by Tichau** [comment]
Hello,
You can reduce the _Maximum number of simultaneous conversion_ to 1, it will lower the CPU usage.

You may have a cooling issue in your PC, maybe try to clean dust in fans or change thermal paste to get back to a normal behavior.
