### ISSUE TITLE
Edge unsafe ?

### ISSUE THREAD

**Issue by Bartmax** [Tichau/FileConverter#203]
SmartScreen is detecting this as unsafe (not on all request, exporadically).

![Screenshot 2021-11-04 095549](https://user-images.githubusercontent.com/3386797/140317285-569f00d5-ea6b-4144-9cbc-d54d8be7e904.png)
![Screenshot 2021-11-04 095600](https://user-images.githubusercontent.com/3386797/140317294-c127ff7e-3d38-4df6-9e9f-19cc3bd2d898.png)

**Comment by Mosquitobrain** [comment]
Edge just seems to do that randomly. People are probably trying attack Github by reporting it.
