### ISSUE TITLE
Couldn't install 32-bit variant on my XP-powered machine.

### ISSUE THREAD

**Issue by saurabhdua82** [Tichau/FileConverter#21]
![clipimage](https://cloud.githubusercontent.com/assets/23373249/25695384/8163a02c-30d0-11e7-9349-bc7ce67a2f0c.jpg)

Pl refer to the enclosed screenshot & help alleviate the Installation pangs. Help will be sincerely appreciated.
Mine is Win XP, SP 3 powered desktop PC & the shown error relates to 32-bit variant of FileConverter.

Web URL f error message - goo.gl/YWHe93

**Comment by saurabhdua82** [comment]
I would request the Hon. Author to please suggest further in the relevant context. Inputs will be greatly appreciated. Thank you.

**Comment by Tichau** [comment]
Unfortunately, File Converter is not compatible with Windows XP. File Converter requires Microsoft .NET Framework 4.5 to be run and it is not compatible with XP (https://blogs.msdn.microsoft.com/dotnet/p/dotnet45xp/).
