### ISSUE TITLE
add .jfif image files

### ISSUE THREAD

**Issue by scooterama** [Tichau/FileConverter#213]
could you add .jfif extensions? Or are those already available?

**Comment by Fl4sHNoX** [comment]
Currently doesn't seem to be available as stated on this page of the wiki:
[https://github.com/Tichau/FileConverter/wiki/Supported-file-formats](Supported file formats)

But I would be interested in it supporting that format as well!

**Comment by tet3** [comment]
JFIF files are JPEGs - if you rename them (say with [PowerToys's PowerRename](https://github.com/microsoft/PowerToys)) then you can convert them to another format.

**Comment by SysAdminDoc** [comment]
> JFIF files are JPEGs - if you rename them (say with [PowerToys's PowerRename](https://github.com/microsoft/PowerToys)) then you can convert them to another format.

That's cool and all, but I want to be able to easily right click and convert without the added step of having to rename each one.

**Comment by Tichau** [comment]
duplicates issue #130
