### ISSUE TITLE
Feature Request: FLAC preset options/parameters

### ISSUE THREAD

**Issue by durhambell** [Tichau/FileConverter#225]
**FLAC files have no options to set in the presets. Would be nice to be able to adjust bitrate and compression.** 

Even nicer would be to use `ini` files or something similar. Then the presets could be easily dropped into another machine with no fuss. Also, this would potentially allow users to set parameters above and beyond those available in the UI. (Will try to open another feature request for that.)

Marvelous utility, good on you! This is, imo, something that ought to have been rolled into Windows in the first place. Cheers!

**Comment by Tichau** [comment]
You can use any parameter you want using the advanced mode.
