### ISSUE TITLE
Add HEIC format support for image conversion

### ISSUE THREAD

**Issue by ricprd** [Tichau/FileConverter#228]
Apple has been recently using HEIC (High Efficiency Image File Format) as its default photo format and it would be great if File Converter supported it when converting image files. More [information here](https://en.wikipedia.org/wiki/High_Efficiency_Image_File_Format).

**Comment by chenstanilovsky** [comment]
+1

**Comment by gzapico** [comment]
+1

**Comment by carlosvsilva** [comment]
Would also like heic support !
