### ISSUE TITLE
Convert .ts video files ?

### ISSUE THREAD

**Issue by BjH14** [Tichau/FileConverter#23]
Hello,
Excellent software ! Very simple and, in the same time, we can change settings if we want !
A question : is it possible to convert .ts video files ? I think not, but is it planed ?
It would be very nice !
Thank you

Bonjour,
Je trouve ce logiciel super pratique ! Depuis le temps que je cherchais un convertisseur (vidéo, surtout) libre et sans installation de pubs... Il est très simple et, en même temps, on peut modifier des paramètres si on le souhaite ! J'en viens à ma question : est-il prévu de pouvoir convertir des fichiers vidéo de format ".ts" ? Ce serait super pratique !
Merci pour tout votre travail.
Bien cordialement

**Comment by Tichau** [comment]
Hi!

Thanks for the feedback :). It was not planned to add .ts files. I add it on my backlog!

Merci ;)

**Comment by BjH14** [comment]
Thank you ! With this possibility, your software will be exactly and totally what I need for the use I have.

Merci beaucoup ! Avec cette possibilité en plus, votre logiciel couvrira complètement tous mes besoins de conversion vidéo et son ! C'est top !

**Comment by nunoperalta** [comment]
Just came here to suggest the same! 👀

**Comment by qubodup** [comment]
I too would love this feature. .ts is one of the file formats offered by OBS (major screen video capture software) and the format apparently is superior due to its support of multiple audio channels (flv doesn't), being recoverable (mp4/mov aren't) and being supported by major video editing applications (mkv isn't).

**Comment by nunoperalta** [comment]
To convert manually, we can use ffmpeg directly:

`ffmpeg.exe -i input.ts output.mp4`

**Comment by steen5500** [comment]
Jeg har lige hentet FileConverter ned på min computer. Virker fint men jeg mangler at FileConverter kan om konvertere TS filer til MP4 eller MKV. Er der planer om at udstyre FileConverter med den funktion ?  (Denmark)

**Comment by ghnp5** [comment]
@Tichau - please see my comment in #379 😊👍🏼
Thanks!!

**Comment by Tichau** [comment]
I've created a ticket to follow the issue: https://github.com/Tichau/FileConverter/issues/387
