### ISSUE TITLE
Download Site Broken

### ISSUE THREAD

**Issue by WhitePhoenixUS** [Tichau/FileConverter#246]
Hmm. We’re having trouble finding that site.

We can’t connect to the server at www.file-converter.org.

If that address is correct, here are three other things you can try:

    Try again later.
    Check your network connection.
    If you are connected but behind a firewall, check that Firefox has permission to access the Web.
UPDATE: You have to leave off the “www.” for some reason. ::facepalm:: Using Firefox 74,0 64 bit

**Comment by bawldiggle** [comment]
Site address is ...
https://file-converter.org/
