### ISSUE TITLE
Will Not Convert Any File with “Error” In Its Name

### ISSUE THREAD

**Issue by WhitePhoenixUS** [Tichau/FileConverter#247]
I just tried to convert a group of WAV files and they all converted except four that had “Error” in there names. After I changed the word to “Arror” File Converter v 1.2.3 converted them with no problem. OS is Windows 7 Professional.

**Comment by Vaelek** [comment]
Just ran into this also "Error words.mp4" failed, "123 - Error words.mp4" failed, "words error.mp4" did not fail
