### ISSUE TITLE
Is this project abandoned ?

### ISSUE THREAD

**Issue by bawldiggle** [Tichau/FileConverter#249]
Last input by the developer Tichau was to add "New Feature" status to issue #144 dated 14-Jan-2021
The previous 104 issues have not been addressed by the developer.

Is the project abandoned ?  In Covid times anything is possible.
In one of my favorite apps ... Zback (dzorc), I sent a support request ... 
and received a very brief email from the developers daughter ... her father had "passed away"

**Comment by ivellios1988** [comment]
Sad to learn this. Maybe someone can fork this program and continue working on it and adding new features?

**Comment by Tichau** [comment]
Hello, 
I can reassure you, I'm still alive. 
I've just a very limited time to work on this project. I am currently planning to release a version with all the fixes and improvements done in the past years.
