### ISSUE TITLE
Does not work on non-admin user. 

### ISSUE THREAD

**Issue by Milagrosamente** [Tichau/FileConverter#284]
I'm trying to install this for a teacher on a managed pc. The only option available is "configure presets," but it does not actually let me save. It works fine on the admin account but I can't get the config to save on the non-admin side, even when the settings file is launched as admin or the whole file is set to have admin rights. Clicking save always leads to a user account control popup, and entering admin credentials doesn't seem to do anything.

**Comment by gustavomags** [comment]
The same problem here.

**Comment by m8urnett** [comment]
See https://github.com/Tichau/FileConverter/issues/22#issuecomment-520825588

**Comment by Tichau** [comment]
duplicates issue #4
