### ISSUE TITLE
Support .tif extension

### ISSUE THREAD

**Issue by cnovel** [Tichau/FileConverter#29]
Hi,
FileConverter supports TIFF files, but only the ones with .tiff extension. Is it possible to add support to .tif files also?
Thanks

**Comment by Tichau** [comment]
Yes it is very possible. I'll add it in the next version.

**Comment by Brainkite** [comment]
TIF extension is not working for me (Ver. 1.2.3)

**Comment by Daseca** [comment]
We often get drawings in tif and that would be awesome with this function to convert it too.

**Comment by coalsand** [comment]
It adds an extra step but you can manually change the file extension from TIF to TIFF and FileConverter will make the conversion.

**Comment by Whoisfoxmulder** [comment]
why is this issue closed but not fixed?

**Comment by Whoisfoxmulder** [comment]
still not working with tif-files - why?
