### ISSUE TITLE
Feature Request: convert multiple documents to a single PDF

### ISSUE THREAD

**Issue by zwackelfuss** [Tichau/FileConverter#295]
Hello, 
I am not sure if this is the right place to ask.. apologies if not :)
I fould FileConverter by chance, it is a great handy tool - thank you for developing and sharing it!

Sometimes I have several docs (different file formats: doc(x), xls, PDF, png, jpg...) to be combined in a single PDF - wouldn't it be great if I could simply select all the files in my explorer window and send them a preset "to CombinedPDF" that merges all documents together and saves that file to the specified folder?

**Comment by Tichau** [comment]
duplicates issue #26
