### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by simlive** [Tichau/FileConverter#299]
Hello author, I am very glad to see that your GitHub file has changed again. I found that Simplified Chinese has been added to the file, which means that the software will continue to be updated in the near future. Will Simplified Chinese meet us? Currently I cannot use the file FileConverter-integration\Application\FileConverter\Properties\Resources.zh-CN.resx. I hope that the author will take time out of his busy schedule to reply after seeing this.

**Comment by Tichau** [comment]
Yes it is plan for the next release that will happen soon :)
