### ISSUE TITLE
Problème dans la création d'un nouveau preset de conversion

### ISSUE THREAD

**Issue by Hopeula** [Tichau/FileConverter#30]
Bonjour

Tout d'abord, je souhaite vous féliciter pour ce programme qui est excellent !!!
Je rencontre un souci dans l'outil de configuration de File Converter.
Le bouton "Enregistrer" est grisé. Je peux créer une nouvelle règle mais je ne peux pas l'enregistrer.
Idem pour les règles existantes, impossible de les modifier car le bouton "Enregistrer" reste toujours grisé.

Si je peux vous apporter plus d'éléments sur ce problème afin de le solutionner, n'hésitez pas à me le faire savoir.

Configuration utilisée : Windows 10 Pro x64 - Core i7 vPro

Capture d'écran ::
![image](https://user-images.githubusercontent.com/31387443/29750703-d76c56d4-8b44-11e7-8783-b5d48c9e2c21.png)

Merci par avance pour votre aide.
Cordialement

**Comment by Tichau** [comment]
I will look at this issue as soon as I have some time.
Do you have admin access to your computer?

Meanwhile, you can change the existing presets (but not creating new ones :/) by editing the XML configuration file in C:/Users/Username/AppData/Local/FileConverter/Settings.xml.

**Comment by Tichau** [comment]
Duplicates of #81 
I keep the new one open since it is writtent in english.
