### ISSUE TITLE
This project is abandoned, any good forks?

### ISSUE THREAD

**Issue by SysAdminDoc** [Tichau/FileConverter#301]
Are there any good forks with updated file formats (ie .jfif) and misc improvements?

**Comment by Toei79** [comment]
+1

**Comment by emilioTejada** [comment]
+1

**Comment by tilsgee** [comment]
+1

**Comment by SkysCrystal** [comment]
+1

**Comment by JackySw** [comment]
I wish Github had a way to compare forks to the original instead of checking all 250 manual. 
FileConverter is a great tool. It deserves some updates. Maybe we need to send more donations?

**Comment by Tichau** [comment]
I'll close all discussions now that there is a space for that in GitHub: https://github.com/Tichau/FileConverter/discussions
