### ISSUE TITLE
[feature request] preset with exact dimension or smaller

### ISSUE THREAD

**Issue by fily1212** [Tichau/FileConverter#310]
Hi! Thank you for your project. It is nice. 
I'd like to suggest a feature: the possibility to specify the maximum dimension of the images. 
For instance I could have 10 images, some of them big and other small. It would be nice to put a threshold of the maximum dimension (x or y) and resize only the bigger one. The 25 - 50% option affects all the images, also the small ones. 

Thank you!

**Comment by Tichau** [comment]
I've added to 720p and to 1080p preset in the default configuration, you can modify these preset to the resolution you prefer.
