### ISSUE TITLE
se podría agregar lo siguiente? // could you add the following?

### ISSUE THREAD

**Issue by jevus122** [Tichau/FileConverter#316]
buenas noches 
se podria añadir la opcion de
abr y cbr 
y poder escribir una cifra exacta en la tasa de bits (kbps) ejemplo 300 para que en cbr se mantenga alli 
y en abr varie entro 150 a 450
tambien la opcion de seleccionar por carpeta ademas de solo archivos 
saludos. 

good night
you could add the option
abr and cbr
and be able to write an exact figure in the bit rate (kbps) example 300 so that in cbr it stays there
and in april I go from 150 to 450
also the option to select by folder in addition to just files
greetings.
![ejemplo](https://github.com/Tichau/FileConverter/assets/133556595/0c5ede91-3cb7-4003-8731-ff8227cf5a91)

**Comment by Tichau** [comment]
It's now possible using the advanced mode
