### ISSUE TITLE
Only options when converting is to configure presets

### ISSUE THREAD

**Issue by ghost** [Tichau/FileConverter#32]
![2017-12-03](https://user-images.githubusercontent.com/19862592/33528043-92e2bda4-d820-11e7-9a9a-898f00cb16d7.png)
I've tried configuring the preset but the preset won't save either, even when i do click save.

**Comment by Tichau** [comment]
Hello, 

It could append if the installation of the software didn't finish well.
At the end of the installation, the installer run the program to initialize the base settings.
This step requires an administrator right elevation since it modifies the registry to be in the contextual menu.

You can try to launch FileConverter with the option `--post-install-init` in a console to reset the settings.
* Go to FileConverter installation folder
* shift + right click and select `Open command line here`
* Type `FileConverter.exe --post-install-init`

Hope it will works

**Comment by lavadragon7i** [comment]
The command line function did not come up, but Windows PowerShell did, so I used that instead, though I'm not sure it's the same.
After putting in the command, FileConverter asks for the administrator password, and then has this error 

![untitled](https://user-images.githubusercontent.com/19862592/33797930-d8689da8-dcd5-11e7-9398-96af5ccbeda0.png)

If I add a typo at the end of "-init", it says "Unknown application argument" but opens FileConverter with a blank screen
![swedrfg](https://user-images.githubusercontent.com/19862592/33797976-8793a2f0-dcd6-11e7-9fb8-63cdd2ae4e0d.png)

Issue still persists 🙁

**Comment by Tichau** [comment]
Strange :/

Did you try to start powershell in administrator mode?

**Comment by lavadragon7i** [comment]
This was done in administrator mode, so yes?

**Comment by Tichau** [comment]
Hello, sorry for the delay. I wish you a happy new year!

It seems that File Converter installer can't modify the registry at the end of the installation.
Here is a registry script that will do the same job: [FileConverterRegistryInitialization.zip](https://github.com/Tichau/FileConverter/files/1596992/FileConverterRegistryInitialization.zip)

Tell me if it solves your issue. You may not be able to create of rename new preset with the File Converter interface only by modifying the registry. Can you tell me more about your setup (windows version, is it an admin account)? 

Cheers

**Comment by lavadragon7i** [comment]
![2018-01-02](https://user-images.githubusercontent.com/19862592/34493360-24fa6bd6-efb1-11e7-820d-474010773941.png)
It worked! Thank you so much! I can't make any new presets, but that's alright with me :')
I'm using Windows 10 and with an admin account.

**Comment by Tichau** [comment]
ok great!
I'll keep this issue open since we just found a workaround.

Can you try to add a new preset, then click apply and then send me the last File Converter diagnostics files?
(you can files diagnostics at C:\Users\<UserName>\AppData\Local\FileConverter\Diagnostics-*)

**Comment by Fylle** [comment]
Hi. I had the same problem. The registry fix posted in this thread worked for me too but same here. Cannot add new presets.
I did try adding a new preset and saving 
but the diagnostics file really does not say anything :/
[Diagnostics1.log](https://github.com/Tichau/FileConverter/files/1751874/Diagnostics1.log)

_Friday, February 23, 2018 14:55:18

File Converter v1.2.3 (64 bits)
Retrieve arguments...
Arg0: C:\Program Files\File Converter\FileConverter.exe
Arg1: --settings

Load settings...
Maximum number of conversion threads: 2
Exit application.
Diagnostics manager released correctly._

**Comment by frederico4d** [comment]
Reg file worked for me too thanks!

**Comment by dhruwal** [comment]
> Hello, sorry for the delay. I wish you a happy new year!
> 
> It seems that File Converter installer can't modify the registry at the end of the installation.
> Here is a registry script that will do the same job: [FileConverterRegistryInitialization.zip](https://github.com/Tichau/FileConverter/files/1596992/FileConverterRegistryInitialization.zip)
> 
> Tell me if it solves your issue. You may not be able to create of rename new preset with the File Converter interface only by modifying the registry. Can you tell me more about your setup (windows version, is it an admin account)?
> 
> Cheers

This worked for me for the same issue. (Non Admin mode)

**Comment by Tichau** [comment]
I've reworked the installer so it can fix this issue. I don't know when I will have a build stable enough to make a version but it will be in the next one for sure :)
