### ISSUE TITLE
Videos modified date

### ISSUE THREAD

**Issue by diegolopezbugna** [Tichau/FileConverter#33]
The converted videos lose the original modified date. So when I add them to google photos, they are not sorted ok,

The converted videos should retain the original's modified date. 

Thanks!! Really love the app!

**Comment by diegolopezbugna** [comment]
I'm using file converter 1.2.3

**Comment by diegolopezbugna** [comment]
The issue also happens to ffmpeg users, there isn't an option on ffmpeg to do it. After the conversion is succesful, the converted file timestamp should be modified to match the original.

**Comment by diegolopezbugna** [comment]
forking and creating a pull request :)

**Comment by Tichau** [comment]
Thanks a lot for your help :)
