### ISSUE TITLE
Weird issue converting Motion JPEGs to mp4 or avi

### ISSUE THREAD

**Issue by diegolopezbugna** [Tichau/FileConverter#34]
I'm using windows 8. FileConverter 1.2.3 64 bit.
After converting Motion JPEGs (taken from two different cameras) to mp4/mkv (h264) or avi (xvid) the thumbnails from file explorer don't show. Just the icon, but not the thumbnail. And with the mp4, If I open it with Windows Media Player or Video app (default win8 video app) the video doesn't show, only the audio. They both open ok with VLC or Zoom player.

If I convert an xvid or another file type to mp4 or avi, there aren't any problems, the thumbnails are generated ok. The issue is only converting from Motion JPEG to mp4/mkv/avi.

Should I try updating some codecs?

**Comment by diegolopezbugna** [comment]
I have updated ffmpeg to 3.4 and still same thing. Tried to do it by the command line, no errors, the same. So it's something on my side or something about ffmpeg.

**Comment by diegolopezbugna** [comment]
Well adding this: -vf format=yuv420p fixed it.
So, I think you should add it to the default settings...
Check http://trac.ffmpeg.org/wiki/Encode/H.264, Encoding for dumb players.
Thanks

**Comment by diegolopezbugna** [comment]
forking and creating a pull request :)

**Comment by Tichau** [comment]
Hello. Sorry for the delay I was not available last days (month ^^).
Thanks for your analysis and pull request!
