### ISSUE TITLE
No Presets Entries for domain member user profile

### ISSUE THREAD

**Issue by bigismike** [Tichau/FileConverter#340]
Hello
W10 22H2 in a windows  domain. standard user account for this domain.
I got a local admin account.
Connected in and installed FC. It works perfectly with presets
Relog to my domain account which is not local admin.
File Converters appears in the context menu only with the "configure presets..." entry.
Added one dont change this.

**Comment by cedtur98** [comment]
Hey,
I seem to have the same issue. Any fix so far ?

**Comment by bigismike** [comment]
Not for the moment

Cordialement

Michel Nolly

_"Il ne faut pas chercher à rajouter des années à sa vie, mais
plutôt essayer de rajouter de la vie à ses années." JFK_

**Comment by uergsel** [comment]
I've got the same issue, working under Win 10  in a windows domain as a standard. 

I even tried the suggestion (from somewhere else) installing it into another folder than C:/Program Files. No result. It only appears the "Configure presets" dialogue.
