### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by inoyakaigor** [Tichau/FileConverter#353]
Since latest release have passed 6 years and there are a bunch of changes. Maybe it's time to release? As beta for example

**Comment by Tsaitou7361** [comment]
#322

**Comment by Tsaitou7361** [comment]
This is the last repository he(Tichau) updated.

**Comment by Tsaitou7361** [comment]
Other repositories are older than this.

**Comment by inoyakaigor** [comment]
Jesus! @Tichau you're alive! 🎉

**Comment by Tsaitou7361** [comment]
> Hello, I'm currently preparing the 2.0 release.

OHHHHHH!!!
