### ISSUE TITLE
Unable to convert AVI files to MP4

### ISSUE THREAD

**Issue by itz-rj-here** [Tichau/FileConverter#362]
![image](https://github.com/Tichau/FileConverter/assets/86042583/c0fbe61b-4942-48f5-a659-dcdaac45c6c3)

**Comment by Tichau** [comment]
Hi,

Can you send the avi file that you did not succeed to convert ?

**Comment by itz-rj-here** [comment]
yup

**Comment by itz-rj-here** [comment]
avi file doesn't supports to add on github so I am adding the file in a online file transfer website
https://www.transfernow.net/dl/20240306lXPgIQeJ

**Comment by itz-rj-here** [comment]
The file will be no longer found after 7 days...
and you are to much late in replying peoples message or reports
I hope you will now reply every single issues, which people are having

**Comment by itz-rj-here** [comment]
![image](https://github.com/Tichau/FileConverter/assets/86042583/44efaae1-5dc3-468e-870a-343aa9bdfd72)
![image](https://github.com/Tichau/FileConverter/assets/86042583/5a4d3095-7d87-440a-a74f-1b9cbc372eb0)
![image](https://github.com/Tichau/FileConverter/assets/86042583/0852ad6b-43c1-479d-89f0-bfcb1c467388)
![image](https://github.com/Tichau/FileConverter/assets/86042583/021ad5e4-70e1-42e8-aaad-f27f633d14ae)

Here are some log details if you need

**Comment by Tichau** [comment]
Is it fixed with the new 2.0 version ?

File to repro the issue:
[FilesToRepro.zip](https://github.com/Tichau/FileConverter/files/14527071/FilesToRepro.zip)
