### ISSUE TITLE
FileConverter website link in about tab

### ISSUE THREAD

**Issue by werdegast** [Tichau/FileConverter#366]
I thought you should know that the website and donation links in the Settings/About tab do not work correctly.

Website goes to www.file-converter.org instead of file-converter.io

Donate goes to pledgie.com/campaigns/31615 and does not open.

Anyway thanks for the great tool.

**Comment by OPADILOP** [comment]
It redirects to the file-converter.io website. 
![image](https://github.com/Tichau/FileConverter/assets/86042583/0bb8809c-779f-416b-92c4-08bab9f31b1e)
