### ISSUE TITLE
Win 7

### ISSUE THREAD

**Issue by harryray33** [Tichau/FileConverter#380]
Does this work with Win 7?

Thanks

**Comment by Tichau** [comment]
Yes it should work with Windows 7 as soon as you have dotnet framework 4.8 installed. Installer should prompt you if this is not the case. 
Here is the link to do it manually: https://support.microsoft.com/en-us/topic/microsoft-net-framework-4-8-offline-installer-for-windows-9d23f658-3b97-68ab-d013-aa3c3e7495e0

**Comment by Komprogue** [comment]
> Yes it should work with Windows 7 as soon as you have dotnet framework 4.8 installed. Installer should prompt you if this is not the case. Here is the link to do it manually: https://support.microsoft.com/en-us/topic/microsoft-net-framework-4-8-offline-installer-for-windows-9d23f658-3b97-68ab-d013-aa3c3e7495e0

Seems like it doesn't work. There is no shell extension on Windows 7 and it can't be run. 

![FC](https://github.com/Tichau/FileConverter/assets/84424346/139cdf0a-bd85-4818-ab84-233f687a0aa3)

**Comment by itz-rj-here** [comment]
@Tichau 

> > Yes it should work with Windows 7 as soon as you have dotnet framework 4.8 installed. Installer should prompt you if this is not the case. Here is the link to do it manually: https://support.microsoft.com/en-us/topic/microsoft-net-framework-4-8-offline-installer-for-windows-9d23f658-3b97-68ab-d013-aa3c3e7495e0
> 
> Seems like it doesn't work. There is no shell extension on Windows 7 and it can't be run.
> 
> ![FC](https://private-user-images.githubusercontent.com/84424346/311109684-139cdf0a-bd85-4818-ab84-233f687a0aa3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NzA5NzIsIm5iZiI6MTcwOTg3MDY3MiwicGF0aCI6Ii84NDQyNDM0Ni8zMTExMDk2ODQtMTM5Y2RmMGEtYmQ4NS00ODE4LWFiODQtMjMzZjY4N2EwYWEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDA0MDQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjMWRlYzkzNDRhNjBiZDAzMDUyMzgyZDk4ZDY4MWRlNWI3ODNkZjBmZjFlM2MzMmI1NjQzZjkyZmQ4ZDUxNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2E7KotEPG90j5abl5osK_OCK3kdOolirgCsLjBXc-u4)

did you installed the dotnet framework 4.8?

**Comment by Komprogue** [comment]
> > > Yes it should work with Windows 7 as soon as you have dotnet framework 4.8 installed. Installer should prompt you if this is not the case. Here is the link to do it manually: https://support.microsoft.com/en-us/topic/microsoft-net-framework-4-8-offline-installer-for-windows-9d23f658-3b97-68ab-d013-aa3c3e7495e0
> > 
> > 
> > Seems like it doesn't work. There is no shell extension on Windows 7 and it can't be run.
> > ![FC](https://private-user-images.githubusercontent.com/84424346/311109684-139cdf0a-bd85-4818-ab84-233f687a0aa3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NzA5NzIsIm5iZiI6MTcwOTg3MDY3MiwicGF0aCI6Ii84NDQyNDM0Ni8zMTExMDk2ODQtMTM5Y2RmMGEtYmQ4NS00ODE4LWFiODQtMjMzZjY4N2EwYWEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDA0MDQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjMWRlYzkzNDRhNjBiZDAzMDUyMzgyZDk4ZDY4MWRlNWI3ODNkZjBmZjFlM2MzMmI1NjQzZjkyZmQ4ZDUxNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2E7KotEPG90j5abl5osK_OCK3kdOolirgCsLjBXc-u4)
> 
> did you installed the dotnet framework 4.8?

Yes, it was already installed. 

UPDATE: After reboot shell integration appears again and it's working.

**Comment by itz-rj-here** [comment]
good

**Comment by Tichau** [comment]
Ok so It seems the installer does not restart explorer correctly. 
It may be the cause of this issue to https://github.com/Tichau/FileConverter/issues/382.

**Comment by Tichau** [comment]
I created an issue to track this problem: https://github.com/Tichau/FileConverter/issues/389
