### ISSUE TITLE
Backup Settings

### ISSUE THREAD

**Issue by ghnp5** [Tichau/FileConverter#381]
Hello,
Thank you so much for the 2.0 release !!

I have been running a number of "ffmpeg" commands myself, keeping a list of useful commands for things that I couldn't do with File Converter.  
Now I can finally save them as presets :-)

However, I'd like to backup/export settings, as part of my regular backup process (for when I switch to another computer in the future, or if disk dies, etc).

Where are the settings saved? Somewhere in registry? Or in a file?

Thank you!

**Comment by Tichau** [comment]
Hello !
Thanks <3

All user files are stored here: %localappdata%\FileConverter\

You also have new import/export actions in the application to export or import a preset or a preset folder (to send it to other users for example). Just right click on it in the interface.

I've created a folder where we can store the preset and create a bank of presets for all users to be shared: https://github.com/Tichau/FileConverter/tree/integration/PresetSamples
If you have some time, don't hesitate to create a pull request adding files to this folder. I'll write some documentation about it when I'll find some time.

**Comment by ghnp5** [comment]
Thank you!

Oh yeah, I noticed I could export specific presets, but it's better to backup the whole thing.

For now, I removed the "reduce 50%" preset I had before, and changed the 75% default presets to 50%, and then changed the 1080p and 760p ones to 340p and 480p, which are the sizes I usually want to resize to. Nothing big :)

Many thanks again!
