### ISSUE TITLE
Windows defender reporting a virus and not allowing download

### ISSUE THREAD

**Issue by rp1231** [Tichau/FileConverter#383]
**Describe the bug**
Windows defender reporting a virus and not allowing download

**Desktop (please complete the following information):**
 - OS: Windows 11 64 bit

**Comment by Tichau** [comment]
Hello, I know it's the same on my side, I've signed the executable with a certificate so I think we need to wait for Microsoft to understand that I'm not a bot. 
Does anyone knows more about windows certificates process ?

**Comment by Tichau** [comment]
This issue is addressed here: #302
