### ISSUE TITLE
HEIC conversion doesn't work

### ISSUE THREAD

**Issue by Baptiste-mrch** [Tichau/FileConverter#388]
**Describe the bug**
No options to convert HEIC files

**Expected behavior**
On the context menu when right-clicking a HEIC file should bring the option file-converter

**Screenshots and Logs**
![image](https://github.com/Tichau/FileConverter/assets/62337736/0d948328-3456-4cdb-ba5f-d1e126f73d8b)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 22H2

**Comment by Tichau** [comment]
This is fixed on integration branch and will be deployed in version 2.0.1
