### ISSUE TITLE
File Converter context menu does not appear after successful install

### ISSUE THREAD

**Issue by Tichau** [Tichau/FileConverter#389]
**Describe the bug**
File Converter context menu does not appear after successful install. 

**Workaround**
After restarting explorer (or your computer) the menu does appear.

**Expected behavior**
After a successful install, File Converter should appear in the context menu of the Windows Explorer.

**Comment by Dweebking** [comment]
I just updated and this is indeed quite the unfortunate bug lol. I think I read that this new version would let me convert files without changing the modified date so I was excited to update since that would be nice for how I browse through my files.

**Comment by Kirshi912** [comment]
I have the same problem but somehow solved it, in my case (win11). When i install the update, the shortcut to convert files disappear then i restarted my file explorer, still context menu didn't appear. So i did open the fileconverter setup again and choose 'repair', after that i restarted my file explorer again... and there is.
