### ISSUE TITLE
Registry Shell Extension to Windows Explorer

### ISSUE THREAD

**Issue by MicheleAwada** [Tichau/FileConverter#391]
Im not sure how to replicate the issue
this software and installation worked on my laptop but trying it on my pc right now its not working
![Screenshot 2024-03-08 195257](https://github.com/Tichau/FileConverter/assets/75516947/ff7c9632-b901-4c45-b19c-69db4f62b830)

its seems to be some error with registry, however when i installed it i hadnt changed the registry yet
heres my .log
[Diagnostics1.log](https://github.com/Tichau/FileConverter/files/14541532/Diagnostics1.log)

if anyone still has any questions ill anwser them

**Comment by ESCracker** [comment]
Yes,i face the same problem, it can't work

**Comment by CrazyBytesVE** [comment]
Same Problem here - Windows 11 23H2.

**Comment by Tichau** [comment]
I've just pushed a version 2.0.1 that change the way installer works, can you tell me if it fixes the issue ?

**Comment by Tichau** [comment]
related to #382

**Comment by CrazyBytesVE** [comment]
> I've just pushed a version 2.0.1 that change the way installer works, can you tell me if it fixes the issue ?

![image](https://github.com/Tichau/FileConverter/assets/16071024/b4fc5b49-3bdc-4bf2-8dd1-42ca52429f0b)

**Comment by SHAHIN2023** [comment]
> I've just pushed a version 2.0.1 that change the way installer works, can you tell me if it fixes the issue ?

Unfortunately, this problem still exists in version 2.0.1

**Comment by MicheleAwada** [comment]
> I've just pushed a version 2.0.1 that change the way installer works, can you tell me if it fixes the issue ?

sadly no
![Screenshot 2024-03-11 191514](https://github.com/Tichau/FileConverter/assets/75516947/27e9e305-9a14-4465-9806-500ed4788959)
