### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by AshiVered** [Tichau/FileConverter#399]
I run the installer and the installation fails. On my old computer, with an older version of FileConverter (but it was also Win11) it worked.

![image](https://github.com/Tichau/FileConverter/assets/76535872/1a585661-9fd2-4789-a416-924b344ab235)
[Diagnostics1.log](https://github.com/Tichau/FileConverter/files/14562152/Diagnostics1.log)

 - OS: 
 
![image](https://github.com/Tichau/FileConverter/assets/76535872/cf299794-0868-49d2-94c1-b69187aafd96)
thanks!

**Comment by Tichau** [comment]
duplicates #382
