### ISSUE TITLE
Preset changes not saved on non-admin session

### ISSUE THREAD

**Issue by gupascal** [Tichau/FileConverter#4]
Hello,

I tried to edit a preset but I got two issues doing it.
- When I try to save my edited preset, a Windows user account control dialog is shown. This is not expected as presets should be editable on a per-user basis.
- Then, even if I successfully validate the previous dialog, the edited preset is not saved. (The next time I open the Setting window, my changes are not here). This issue appears only using a non-admin user.

I hope this help, and btw your file converter is a really great initiative.

Thanks.

**EDIT:**
In case it can help, I am on Windows 10 x64.
Also, no conversion options are available in the explorer context menu using the non-admin account. (No problem with the admin account).

**Comment by Tichau** [comment]
Hello,

Thanks for your feedback ! I never tried File Converter on a non-admin account so your feedback is really helpful.

Normally you should be able to edit existing conversion presets without admin right (without changing the input types and renaming the preset).
I use admin rights to be able to modify the windows explorer menu in the registry (to add new compatible formats and new preset).

I'll test the software on a non-admin account and try to find a solution for editing presets with restricted permissions but it was not designed to be possible.

Thanks again.

**Comment by janthefactor** [comment]
Hello,

I have exactly the same issue as gupascal, down to every detail. Indeed this program is a great initiative! 

Best regards and thanks.

**Comment by ellisgeek** [comment]
Yep I just ran into this as well, same issue as gupascal and janthefactor. I was going to use this as an easy solution for a user that needs to shrink some images occasionally.

**Comment by Manni79** [comment]
Thanks for cleaning up the tickets. Some are linked to this topic here, that FileConverter only works if you have admin rights. 
I think it would be great if this would be adjusted, especially since (in my opinion) there are many user without admin rights on the PC. 
And also according to security guidelines to use accounts without admin rights as long as you don't need them. So, it would be great, to see FileConverter usable without an admin privilages.

**Comment by Tichau** [comment]
Yes I agree with you, I think this will be my next focus, but I don't know when I will have time to work on this.

**Comment by Manni79** [comment]
Happy new year! 
Any news or target date? Still can't use it (because no admin privilages). :-(

**Comment by arihant23** [comment]
+1 For fixing this issue

**Comment by genkadama** [comment]
is version 1.2.4 still scheduled?

**Comment by thipau** [comment]
Same problem with non-admin user.
Any fix release scheduled?
