### ISSUE TITLE
No preset saving possible

### ISSUE THREAD

**Issue by ncssche** [Tichau/FileConverter#40]
Very useful program in general but one important thing doesn't work:
On my PC  (Win10/64bit built 1709 - admin rights) the button for saving presets is greyed and it's not possible to save a preset (the inbuilt presets work for converting files, by the way). 
What I tried so far: changing the rights of FileConverter.exe to full (just to be sure), running the RegistryInitialization.reg manually (the settings have been accepted by the registry). The Log file says:
"The number of processors on this computer is 4. Set the default number of conversion threads to 4
Maximum number of conversion threads: 4" - but where can I change this (if this is the cause for the problem)?
Thanks in advance!

**Comment by Tichau** [comment]
Hello,

Sorry for the late response. I have finally found some time to work again on File Converter, I will look at your issue as soon as possible. Can you provide me the log files when the problem happen?

**Comment by MikeFl1** [comment]
Sure, I would be glad to provide the Log Files. Tell me how to do that please.


________________________________

**Comment by ncssche** [comment]
Hello,

the problem is NOT that it does no conversion - problem is that I cannot
save a preset after editing it (the save button is greyed and doesn't
work).
But in the meantime I found a way to change preset settings in the
settings.user.xml manually. I think the problem has to do with Windows
rights (at least here under Win10 prof./64bit). What about storing the
settings.user.xml in the install directory instead of appdata/local?

Good work though and good luck!
Norbert

**Comment by Tichau** [comment]
Hello,

Try to launch fileconverter with the apply-settings option to force the settings application, then send me the more recent diagnostic folder.
You will find the diagnostics folder in `c:\Users\[UserName]\AppData\Local\FileConverter\`.

use the command
`C:\Program Files\File Converter\FileConverter.exe --apply-settings`

**Comment by ncssche** [comment]
[Diagnostics-23h48m30s.zip](https://github.com/Tichau/FileConverter/files/2489430/Diagnostics-23h48m30s.zip)
Hello - here is the latest diagnostics folder ...

**Comment by ncssche** [comment]
again ...
[Diagnostics-23h48m30s.zip](https://github.com/Tichau/FileConverter/files/2508672/Diagnostics-23h48m30s.zip)
