### ISSUE TITLE
Error when trying to install

### ISSUE THREAD

**Issue by KitsuTheFloof** [Tichau/FileConverter#401]
![image](https://github.com/Tichau/FileConverter/assets/90358192/a9194f26-33ef-4357-b4e5-a1228316c13c)

**Comment by XBrayanX** [comment]
I have the same problem with windows 11

**Comment by digitalcoyote** [comment]
As a workaround, try installing v1.2.3 first then upgrade to 2.x
#382 is currently tracking an issue with the extension registering on install (only occurs if it hasn't previously been registered) a fix is in the works
