### ISSUE TITLE
Update Chocolatey version to 2.0.2

### ISSUE THREAD

**Issue by cnovel** [Tichau/FileConverter#404]
**Is your feature request related to a problem? Please describe.**
I'm installing most of my software through Chocolatey, including FileConverter.

**Describe the solution you'd like**
[Update FileConverter on Chocolatey](https://community.chocolatey.org/packages/file-converter) (currently v1.2.3.20210111)

**Describe alternatives you've considered**
I could install FileConverter manually, but Chocolatey helps me keeping my softs up-to-date.

**Additional context**
/

**Comment by Tichau** [comment]
This is already in progress, this has been done by @digitalcoyote, you can follow the review process here: https://community.chocolatey.org/packages/file-converter/2.0.2

**Comment by Tichau** [comment]
done since 17 mars
