### ISSUE TITLE
Publish the app to Microsoft Store

### ISSUE THREAD

**Issue by Kenya-West** [Tichau/FileConverter#43]
Microsoft Store is one place for everything in your life, moving your experience to a safe one and making it accessible from many devices that added to your Microsoft account.

Publishing apps to Microsoft Store is benefit both for users and developers + enterprise. Deploying classic apps, that available in Microsoft Store, with safe methods to a verified environments is trusted by enterprises and users. From the other hand, developer can benefit from "In-App Purchase" (paid features of the app), making its own Insider programs, setting up subscriptions and advertisements.

Microsoft corporation has opened a door to developers of classic apps, the way to publish your app to Microsoft Store. UWP brings a second life for your apps: notifications, full power of trusted UWP/WinRT API, easy debug, easy deploy, additional features.

Learn more about that easy process [here](https://developer.microsoft.com/windows/bridges/desktop).

Best regards,
Innokenty Ivanov,
North-Eastern Federal University student (Master degree).
Programmer, web developer, **Microsoft Student Partner**.
My [e-mail](mailto:Kenya-West@outlook.com).

**Comment by Tichau** [comment]
Thanks for the suggestion
