### ISSUE TITLE
File Converter not working after uninstall & re-install

### ISSUE THREAD

**Issue by TheOtherUniqueDave** [Tichau/FileConverter#46]
I uninstalled File Converter on Windows 10 PC (it was working file but I was trying to pin down an annoying Windows issue by removing things) then tired to re-install it. Surprisingly File Converter didn't re-appear in the explorer context menu after re-running the installer. 
Additionally, if I try to change the defaults (e.g. disable png to jpg conversion) the settings dialog simply vanishes when I press the Save button (I suspect it's crashing when I hit Save).
Repairing and re-installing haven't made any difference.
(The user has admin rights)
Any ideas?

**Comment by Tichau** [comment]
Hello,

Can you re-try to disable png to jpg convertion and then send me the more recent diagnostic folder?
You will find the diagnostics folder in c:\Users\[UserName]\AppData\Local\FileConverter\.

**Comment by bazarus** [comment]
same thing. File converter didn't appear in context menu windows 7.

**Comment by Marooned-MB** [comment]
Hi, I'm bumping this issue. I have Windows 7 and I've noticed I do not have FC in context menu. I run the installer and `repair`, it didn't help. I then uninstalled and installed again newest FC. Still nothing. I can run FC settings and change it. All .xml and Diagnostics are written in the folder correctly. Any help? Thanks
