### ISSUE TITLE
CAN NOT INSTALL IN WINDOWS 7 x86 version 6.1 7601 SP1

### ISSUE THREAD

**Issue by ysharoiko** [Tichau/FileConverter#47]
[f.log](https://github.com/Tichau/FileConverter/files/1844252/f.log)

=== Logging stopped: 24.03.2018  12:59:41 ===
MSI (c) (38:44) [12:59:41:131]: Note: 1: 1708 
MSI (c) (38:44) [12:59:41:131]: Note: 1: 2205 2:  3: Error 
MSI (c) (38:44) [12:59:41:131]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1708 
MSI (c) (38:44) [12:59:41:132]: Note: 1: 2205 2:  3: Error 
MSI (c) (38:44) [12:59:41:132]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1709 
MSI (c) (38:44) [12:59:41:132]: Product: File Converter (32 bit) -- Installation failed.

MSI (c) (38:44) [12:59:41:134]: Windows Installer installed the product. Product Name: File Converter (32 bit). Product Version: 1.2.3. Product Language: 1033. Manufacturer: Adrien Allard. Installation success or error status: 1603.

MSI (c) (38:44) [12:59:41:139]: Grabbed execution mutex.
MSI (c) (38:44) [12:59:41:139]: Cleaning up uninstalled install packages, if any exist
MSI (c) (38:44) [12:59:41:141]: MainEngineThread is returning 1603
=== Verbose logging stopped: 24.03.2018  12:59:41 ===

**Comment by ysharoiko** [comment]
Everything WAS SOLVED after running AS ADMINISTRATOR )
And installing NET FRAMEWORK. Do not know is both of it is requered, or just admin is enough )

**Comment by Tichau** [comment]
.net framework 4.5 is required so yes both are needed :)
