### ISSUE TITLE
Could not install in Windows XP 32 bit  build 2600.xpsp.080413-2111: Service Pack 3

### ISSUE THREAD

**Issue by ysharoiko** [Tichau/FileConverter#48]
[log.log](https://github.com/Tichau/FileConverter/files/1889272/log.log)
[log1.log](https://github.com/Tichau/FileConverter/files/1889273/log1.log)

**Comment by Tichau** [comment]
Unfortunately, File Converter is not compatible with Windows XP. File Converter requires Microsoft .NET Framework 4.5 to be run and it is not compatible with XP (https://blogs.msdn.microsoft.com/dotnet/p/dotnet45xp/).

**Comment by MikeFl1** [comment]
I'm using W10 and have .NET FRAMEWORK VERSION 4.7.2556.0 and .NET Framework 4.0.41210.0 (32/64-bit). When I open FileConverter by double clicking on the FileConverter-1.2.3-x64-setup.msi file, a Password request window opens on top of the FileConverter work page and without a password I cannot proceed.
