### ISSUE TITLE
I am prompted to fill out a password as soon as FileConverter opens

### ISSUE THREAD

**Issue by MikeFl1** [Tichau/FileConverter#49]
Is this a github password or from the developer? I don't know what the password is.

![20180505_091512](https://user-images.githubusercontent.com/39009196/39664812-b17cd012-5046-11e8-8a8a-6432d233a45f.jpg)

**Comment by Tichau** [comment]
Hello,

This is very strange. I did not write any code to show this kind of popup.
This may be a hacked version, where did you download the installer ? is the installer signed with my name ?

**Comment by MikeFl1** [comment]
I downloaded it from here (see attachments):

https://github.com/Tichau/FileConverter

[https://avatars2.githubusercontent.com/u/3792144?s=400&v=4]<https://github.com/Tichau/FileConverter>

GitHub - Tichau/FileConverter: File Converter is a very ...<https://github.com/Tichau/FileConverter>
github.com
GitHub is where people build software. More than 27 million people use GitHub to discover, fork, and contribute to over 80 million projects.





________________________________

**Comment by Tichau** [comment]
I don't see any files in the attachments

**Comment by Tichau** [comment]
It seems that this is a password of another software. Maybe a virtual machine, I kind of recognize the icon of virtual box. 
This is not an issue in File Converter, *there is no password to type to make File Converter works*.

I close this issue. If you have any question don't hesitate ta ask.
