### ISSUE TITLE
Default Conversion Presets After Update

### ISSUE THREAD

**Issue by wolfsubak** [Tichau/FileConverter#5]
When I updated to last version some default valued changed in preset.
For example the "To small PNG (25%)" was 1600%.

Huge surprise to see multiple 42GB files poping on disk.

[Here a list a of screenshots taken](https://twitter.com/Wolfheimrick/status/788769647692615680)

**Comment by Tichau** [comment]
Indeed it's not normal ^^.
I will look into that issue. 

Thanks for your report !

**Comment by Tichau** [comment]
I finally found the cause of this bug. 
I'll try to push a fix asap.

Thanks again
