### ISSUE TITLE
Saving not possible

### ISSUE THREAD

**Issue by CG364** [Tichau/FileConverter#50]
When i try to save a preset the "Save" button is disabled.
This started happening around a few weeks ago.
My earlier made presets are still there

**Comment by Tichau** [comment]
related to issue #40

**Comment by MikeFl1** [comment]
I have receiver 10 emails in the last 24 hours that were not related to the issue I was having, and have never received a solution to the issue I asked about in May of 2018 about not being able to open FileConverter due to a password request screen.
________________________________

**Comment by Tichau** [comment]
I'm currently trying to work again on the project so i'm cleaning the issue board and try to prioritise them, that is why you're receiving a lot of email. 

As a reminder, this project is a personal project, I'm not payed to maintain it, I try to do my best in my spare time but I can't garantie you that I will fix your issue.
