### ISSUE TITLE
Link to website is incorrect.  

### ISSUE THREAD

**Issue by scottbragg** [Tichau/FileConverter#51]
The link on the top of this git repo: 

http://www.file-converter.org

gives a dns error in the browser.   Dns lookup shows this as well: 

`# host www.file-converter.org
Host www.file-converter.org not found: 3(NXDOMAIN)`

Removing the host from the url  (ie.. www)  corrects this issue.  

`# host file-converter.org
file-converter.org has address <ip>`

The current correct url is  https://file-converter.org

**Comment by Tichau** [comment]
Thanks you for this report.
It's now fixed :)

**Comment by MCOfficer** [comment]
FWIW the github homepage link (not the README, the github metadata) is still www.
