### ISSUE TITLE
De-Interlace

### ISSUE THREAD

**Issue by louisvangeldrop** [Tichau/FileConverter#53]
I use a DV Video film from a Sony Camera. With VLC 3.0.3 I have imported the file into my pc. However when I convert the file, the movie needs deinterlacing. If I convert with  ffmpeg with the yadif parm it works fine. However I prefer to use the File Converter, since it is very user friendly. 
Any suggestion ?

**Comment by Tichau** [comment]
Hi,
Can you send me a small sample video so I can add this option in File Converter and test it?

**Comment by louisvangeldrop** [comment]
Hallo Adrien,

Unfortunately these files imported DV-video’s with an average size of 12 GB. I have imported the files with aSony camera over a firewire-cable using the Sony software. FFMpeg supports a deinterlace option, which I used to convert the file to mp4 format.

Brgds,
-Louis

Van: Adrien Allard <notifications@github.com>
Verzonden: maandag 22 oktober 2018 08:16
Aan: Tichau/FileConverter <FileConverter@noreply.github.com>
CC: Louis van Geldrop <louis@vangeldrop.com>; Author <author@noreply.github.com>
Onderwerp: Re: [Tichau/FileConverter] De-Interlace (#53)


Hi,
Can you send me a small sample video so I can add this option in File Converter and test it?
