### ISSUE TITLE
Donation site dead

### ISSUE THREAD

**Issue by ferousFolly** [Tichau/FileConverter#57]
Not a bug or anything back-end, but I would like to donate a few bucks or so due to how useful this is to me. Unfortunately, the site that is being used as a donation receptor is archived as of February 2018. No loss to me if this isn't looked at, but it could be good for the devs to change.

**Comment by rmenessec** [comment]
Project seems dead. Last commit was 2017-04-29.

**Comment by Tichau** [comment]
The new link for donation is on [paypal](https://www.paypal.com/donate/?cmd=_donations&business=3BDWQTYTTA3D8&item_name=File+Converter+Donations&currency_code=EUR&Z3JncnB0=)
