### ISSUE TITLE
I am not getting a menu

### ISSUE THREAD

**Issue by grandma78633** [Tichau/FileConverter#68]
Installed the file converter and tried the Repair option.  But when I right click on a file, the only option when I choose File Converter is "Configure Presets"

**Comment by ICT4ALL** [comment]
Exactly the same issue here.  I have saved my presets and entered the elevated admin password (as my windows user is not an admin) but the second time I right click the "Configure Presets" is still the only option.  Windows 8 64bit.  Used 64bit installer MSI V1.2.3

**Comment by ICT4ALL** [comment]
I thought my issue may be bacuae i was right clicking on a WMA file to convert which may not be supported but tried again on a PNG and JPG file and still had the same issue.

Can I manually check a config file to check if my configuration is being written correctly when I elevate my access level?

**Comment by ggendronTA** [comment]
Same issue here with the same configuration (my user is not admin).
I even tried to install FileConverter on a folder on which I have rights (out of program files), and still... the context menu is empty.

**Comment by Tichau** [comment]
It seems that this issue is the same than this one #32 

I propose a temporary solution in order to be able to use File Converter in this issue.

**Comment by tryrebooting** [comment]
![2020-02-06_12-06-20](https://user-images.githubusercontent.com/32101545/73960623-3f942d00-48d9-11ea-8eec-77c75e814397.jpg)

This is the only option I see.
Non-Admin account.
Windows 10 Pro 64-Bit
Version 1909
