### ISSUE TITLE
Convert transparent PDF/PNG to JPG got black background

### ISSUE THREAD

**Issue by dieptp** [Tichau/FileConverter#69]
I got a problem with convert transparent PDF/PNG to JPG. This application have not option to changing background color while convert transparent object. So everytime I try to convert to JPG, it's background became black :(
Could you help me, please!
![capture](https://user-images.githubusercontent.com/31943859/53536018-4ea22500-3b37-11e9-9475-bd0a153a0413.PNG)

**Comment by dieptp** [comment]
Here's origin files.
[https://1drv.ms/f/s!AjGwUgj-J6JKitQImkcCHilqUj9ZZg](url)
thanks for any help

**Comment by Tichau** [comment]
Hello,

This is a good suggestion, this can be nice to customize the background color.

**Comment by Tichau** [comment]
Duplicates #66

**Comment by getopian** [comment]
Will you fix it?
