### ISSUE TITLE
New Installer

### ISSUE THREAD

**Issue by TheAresjej** [Tichau/FileConverter#7]
Change MSI installer to EXE and make new images

**Comment by Tichau** [comment]
What do you mean about making new images ?

**Comment by TheAresjej** [comment]
You can copy ;)
http://imgur.com/a/jnQcb

**Comment by Tichau** [comment]
I made some of the improvements you suggested in the 1.2.1 version installer.

Why do you want to rename the msi extension to exe ?

**Comment by TheAresjej** [comment]
the most common problem in msi is the "Internal Error 2502 / 2503" exe not have this problem

**Comment by Tichau** [comment]
Ok thanks, I will look at that.
