### ISSUE TITLE
Option to change chroma subsampling during conversion

### ISSUE THREAD

**Issue by djcurley89** [Tichau/FileConverter#73]
Need a way to convert a 4:2:2 video file to 4:2:0 MP4, I know it's possible through ffmpeg command line, but need a way to do it through this application. Thanks!

**Comment by Tichau** [comment]
It is not possible for now. 
Maybe I will add this possibility in future versions.

Thanks for the feedback :)

**Comment by Tichau** [comment]
You can now create a custom preset using the advanced mode. You can find all ffmpeg option here: https://ffmpeg.org/ffmpeg.html
