### ISSUE TITLE
[suggestion] add pdf to word conversion

### ISSUE THREAD

**Issue by malis2007** [Tichau/FileConverter#78]
it would be great if one was able to convert pdf to word :)
so far, this tool works brilliantly and no issues faced.
Thanks for this awesome tool. <3

**Comment by Tichau** [comment]
Hello! Thanks for the suggestion.

Honnestly I don't even know if it's even possible to do this kind of conversion.
I'll close the issue since I have no solution for this. i'll reopen it if I find something.

Thanks anyway for the suggestion!

**Comment by asyba** [comment]
"Honnestly I don't even know if it's even possible to do this kind of conversion." ??
Why? This is the most request functionality that everybody wants.
There are a lot of apps that do this but are not free.

**Comment by BenignPigeon** [comment]
It's definitely worth looking at this open source repo for this https://github.com/ArtifexSoftware/pdf2docx

Perhaps you could use this as a backend for this.

python -c "from pdf2docx import Converter; cv = Converter(r'!pdf_path!'); cv.convert(r'!output_path!'); cv.close(); print('Conversion complete! Output:', r'!output_path!')"
