### ISSUE TITLE
Mini Redesign

### ISSUE THREAD

**Issue by TheAresjej** [Tichau/FileConverter#8]
If you like it then you can add it :D

Header:
http://imgur.com/Yxh3nDx

About:
http://imgur.com/RpLZZB1

**Comment by Tichau** [comment]
Nice :) !
I like all your changes (except for the switch of the picture/text in the about section).

Can't you send me your assets (icons) ? by pull request or in this issue.

Thanks for your help :) 
I hope you like the soft

**Comment by TheAresjej** [comment]
Icons Download:
https://goo.gl/yiZy1e

**Comment by Tichau** [comment]
Do you have the icon in svg format ? it will be easier to manipulate :)

**Comment by TheAresjej** [comment]
I do not have :(

**Comment by Tichau** [comment]
I made some of the improvements you suggested in the 1.2.1 version :)
