### ISSUE TITLE
Save doesn't work

### ISSUE THREAD

**Issue by Kreezie** [Tichau/FileConverter#81]
When I enter a new preset, the Save buttong stays lightgrey, it doesn't work.....

**Comment by Tichau** [comment]
Hello, thanks for the report. This issue has already been reported in #30 but the description is in french so I will keep this one open to track the issue and close the other.

I will look at this issue as soon as I have some time.
Do you have admin access to your computer?

Meanwhile, you can change the existing presets (but not creating new ones :/) by editing the XML configuration file in C:/Users/Username/AppData/Local/FileConverter/Settings.xml.

**Comment by Kreezie** [comment]
Thanks for the reply. And yeah, I don't speak French, so I didn't see the
other report.

I will go and play a bit with the xml-file, and wait till the issue has
been taken care of. Just for fun ;-) because I can do what I wanted (jpg to
smaller jpg) in two steps, first convert to smal png and then convert to
jpg.

By the way, I love the program!

Thans again,
Kees
<https://keeskouwenberg.nl/>


Op vr 26 apr. 2019 om 19:48 schreef Adrien Allard <notifications@github.com

**Comment by nate101pro** [comment]
I found a fix for this bug, hopefully this will fix it for everyone else that has it as well.
Some of the default presets have a invalid file name template, look through all of them and change the special path, its that easy. 

Shown in the screenshot, for me it was "my musics path" (p:m) for extracting CDAs.
![Screenshot (28)](https://user-images.githubusercontent.com/33772352/100216440-49c2fe80-2ee0-11eb-8413-79a505473393.png)
Simply changing the (p:m) to (p:d) worked for me or you could just delete the preset altogether.

I think the cause of this is the program cant map a path to any other drive then the **OS (C:)** which my music and videos have their own dedicated hard drive and are not located there like my documents. #

**Comment by Kreezie** [comment]
YAY!!!! Worked for me too, tnx!!!
