### ISSUE TITLE
Maximum files limit?

### ISSUE THREAD

**Issue by warmwhisky** [Tichau/FileConverter#86]
I cannot seem to get this to work when I select 460 files. Seems to work with a few like 20 or so.

It has been working fine until today I installed on a windows 10 server workstation. When I choose my preset there is just no response. I tried it on a folder that was not so deep in the server and still the same. Strangely the "configure presets" is also not popping up when I click it after it has failed.

Seems to be doing it on my Windows 7 machine also. 

I am trying to downsize jpg by 25% only.

**Comment by ivellios1988** [comment]
Same thing happened to me on Windows 10. File Converter just didn't start until I deselected some files.

**Comment by Cipriux** [comment]
I think I found the reason:
The selected files full path should not be bigger than 31k something characters
Here is my exact example with empirical testing, this is the exact maximum limit that works on my selections
So there are 445 files selected with the following path structure of maximum character size: 31793 + 445 \n = 32238
--------
001:f:\2_Downloads\down_net\_MJ_temp\123456789_123456789_123456789_001.png
001:f:\2_Downloads\down_net\_MJ_temp\123456789_123456789_123456789_002.png
...
444:f:\2_Downloads\down_net\_MJ_temp\123456789_123456789_123456789_444a.png
445:f:\2_Downloads\down_net\_MJ_temp\123456789_123456789_123456789_445a.png
------
I used Total Commander to copy file path list and Sublime Text with LaTeX Word Count plugin to count the characters
I hope it helps anyone

**Comment by Tichau** [comment]
Since FileConverter is launch by command line, there is a limitation about the size the string containing the arguments.

To allow more conversion to be done, we should implement a way of passing files to convert in a text file.

**Comment by mesheets** [comment]
Might there perhaps be a way to have FileConverter act on files in a directory, possibly with a recursive option?  For example, provide:
* Directory path
* File type/extension to convert
* Conversion preset identifier/name
* Recursive: yes or no

In @Cipriux's example, the files all appear to be under the directory "F:\2_Downloads\down_net_MJ_temp\", so a directory-based approach potentially might address that use case.

**Comment by Tichau** [comment]
This request has been done here if you want to had info: issue #94
