### ISSUE TITLE
Feature Request: HEIC file converter

### ISSUE THREAD

**Issue by ChimpRocket** [Tichau/FileConverter#96]
Hi,

As iPhone preferred photo format is HEIC and OneDrive is moving over to HEIC for Camera Roll sync, I often find myself having to convert files to JPG . Often this is due to compatibilty issues with the likes of eBay's website which doesn't support HEIC. Can you add a convertor for this please? Obviously it will only work on computers with a HEIC codec.

Love your convertor btw :-)
Thanks!

**Comment by GrantErickson** [comment]
Super useful request. Would love to see this as well.

**Comment by chadericstevens** [comment]
> Super useful request. Would love to see this as well.

-- Ditto

**Comment by Mr-ph422** [comment]
Yep! I agree to them^. That would be great.

**Comment by softlion** [comment]
Agree !

**Comment by danemorgan** [comment]
Adding my support for this addition.

**Comment by theoryshaw** [comment]
+1

**Comment by LastRoze** [comment]
Please make this happen, I'm tired of using those online converters since I use this software for a long time and don't want to use another one!

**Comment by softlion** [comment]
> Please make this happen, I'm tired of using those online converters since I use this software for a long time and don't want to use another one!

You can try IrfanView 64
It supports HEIC and batch conversion does work.

**Comment by Marooned-MB** [comment]
Are there any plans for heic support? This is quite an old thread and no info has been provided so I'm just curious. Thanks!

**Comment by moquito64** [comment]
+1

**Comment by ScottHollows** [comment]
+1

HEIC has been around for a few years and I dont know anyone that likes it. Please add support to convert from HEIC to other formats.
