### ISSUE TITLE
Add chocolatey package

### ISSUE THREAD

**Issue by xerus2000** [Tichau/FileConverter#97]
Any chance of adding this to chocolatey to easily install and update it?

**Comment by digitalcoyote** [comment]
[file-converter](https://chocolatey.org/packages/file-converter/1.2.3) has been submitted to Chocolatey. It will probably take a bit to go through moderation. I'll keep this up to date, but if hte mainter of this project would like management rights to the package, let me know your Chocolatey username and I'll add you (adds some credibility to the package as well).

**Comment by Tichau** [comment]
Hello, Thank you @digitalcoyote for submitting File Converter to chocolatey. Here is my chocolatey account https://chocolatey.org/profiles/Tichau

**Comment by digitalcoyote** [comment]
@Tichau I've added you as a maintainer on Chocolatey. Left as is, if you release a new version on GitHub, it will automatically upload to chocolatey as well using the scripts found in the package source link (a Chocolatey AU repo).

**Comment by Tichau** [comment]
Ok nice! Thank you! I close this issue :)
