### ISSUE TITLE
Does not recognise input files

### ISSUE THREAD

**Issue by xerus2000** [Tichau/FileConverter#98]
Regardless of where I right-click on, the menu only has the option "Configure presets...", no conversions - I'm on Windows 7

**Comment by tryrebooting** [comment]
I am having same experience.
Installed, UAC prompt, save configuration preset.
Right click on file to convert only shows 'Configure Presets'.

Windows 10 Pro 64-Bit
v.1909

**Comment by Tichau** [comment]
Duplicates issue #32
